service: python-serverless-app

provider:
  name: aws
  runtime: python3.8
  stage: v1
  region: us-east-1
  timeout: 30
  memorySize: 256
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**

functions:
  app:
    handler: ./src/handler.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline 
